stages:
  - "build"

build-project:
  image: "maven:3.9.9-eclipse-temurin-8"
  stage: "build"
  script:
    - "mvn clean package"
  artifacts:
    paths:
      - "/target/SymPreProc-1.0-SNAPSHOT-jar-with-dependencies.jar"
  tags:
    - "maven"
    - "java"